# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Gems
gems: [jekyll-paginate, jekyll-gist]

# Setup
title:            dchen71
tagline:          'Lost in a sea of electrons'
description:      'Aspiring software engineer swimming in a sea of electrons'
url:              dchen71.github.io
baseurl:          /

author:
  name:           'Daniel Chen'
  url:            dchen71.github.io

paginate:         5
paginate_path: "page:num"

# Custom vars
github:
  repo:           https://github.com/dchen71
linkedin:
  link:			  https://www.linkedin.com/in/daniel-chen-6a97aa62