# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            dchen71
tagline:          'Lost in a sea of code'
description:      'Aspiring software engineer lost in all manners of code'
url:              dchen71.github.io
baseurl:          /

author:
  name:           'Daniel Chen'
  url:            dchen71.github.io

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/dchen71
